import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/lib/providers/StoreProvider";
import ToastProvider from "@/lib/providers/ToastProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <StoreProvider>  
        
        {children}
       <ToastProvider/>
        </StoreProvider>
      </body>
    </html>
  );
}
